[package]
name = "lilypads"
version = "0.11.1"
edition = "2024"
description = "Fun little object pool allocator."
repository = "https://github.com/Karanstr/lilypads"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
paste = "1.0"
